### ISSUE TITLE
Why not tags?

### ISSUE THREAD

**Issue by chaitanyathengdi** [naturalprogrammer/np-spring-tutorial#1]
Hi there Mr Patel.
Even though I'm an experienced Git user, seeing so many branches confused me a bit. Why, instead of
 branches, are tags not used? It'd seem like the obvious choice for the progression of your first module.

**Comment by naturalprogrammer** [comment]
Hello, thanks for the suggestion. I actually patch the branches as Spring
progresses. Not sure if tags would allow me to do that, would they?

Thanks,
Sanjay

NaturalProgrammer.com <http://naturalprogrammer.com/>

**Comment by chaitanyathengdi** [comment]
I don't usually use patches; but if you mean a git merge(and I think you do, based on the output of gitk), yes you can, since it's just a ref.

**Comment by chaitanyathengdi** [comment]
Additionally tags("releases" in GitHub) will allow users to download progressive zip files. If I were to download a zip from your repo's main page, I'd get the entire repo, which I may not want.

**Comment by naturalprogrammer** [comment]
Okay, thanks for trying to help! I currently have links in the book, e.g.
https://github.com/naturalprogrammer/np-spring-tutorial/tree/hello-world ,
which points to branch that I keep moving forward. So, the link won't break
even if I push things into the branch.

The same is possible with tags, you mean?

Thanks,
Sanjay

NaturalProgrammer.com <http://naturalprogrammer.com/>

**Comment by chaitanyathengdi** [comment]
Tags are static, so they won't change after you create them, and they point to a specific commit. After pushing to GitHub, you can't change your commits, so a static link pointing to a commit is useful for marking progress.

The only difference between a tag and branch is that you can push to a branch but not to a tag; you need to create a new tag.

**Comment by naturalprogrammer** [comment]
Okay, then I guess I've to use branches so that I can keep committing to
those without breaking the links in the books. No?

Thanks,
Sanjay

NaturalProgrammer.com <http://naturalprogrammer.com/>

**Comment by chaitanyathengdi** [comment]
If you keep committing, then branches.
